# Generated by Django 3.0.6 on 2020-05-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200513_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizzaPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_toppings', models.CharField(max_length=64)),
                ('small_price', models.FloatField()),
                ('large_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizzaPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_toppings', models.CharField(max_length=64)),
                ('small_price', models.FloatField()),
                ('large_price', models.FloatField()),
            ],
        ),
    ]
