# Generated by Django 3.0.6 on 2020-05-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_dinnerplatter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegularPizzaPrice',
            new_name='RegularPizza',
        ),
        migrations.RenameModel(
            old_name='SicilianPizzaPrice',
            new_name='SicilianPizza',
        ),
    ]
