# Generated by Django 3.0.6 on 2020-05-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200515_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('small_price', models.FloatField(default=None)),
                ('large_price', models.FloatField(default=None)),
                ('price_per_topping', models.FloatField(blank=True)),
                ('available_toppings', models.ManyToManyField(blank=True, related_name='availableToppings', to='orders.Topping')),
            ],
        ),
    ]
