# Generated by Django 3.0.6 on 2020-05-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='price_per_topping',
        ),
        migrations.AddField(
            model_name='sub',
            name='price_per_topping_large',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='sub',
            name='price_per_topping_small',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.FloatField(),
        ),
    ]
