# Generated by Django 3.0.6 on 2020-05-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200516_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.FloatField(blank=True),
        ),
    ]
