# Generated by Django 3.0.6 on 2020-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200517_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='available_toppings',
            field=models.ManyToManyField(blank=True, default=None, related_name='availableToppings', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.FloatField(blank=True, default=None),
        ),
    ]
