# Generated by Django 3.0.6 on 2020-05-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200517_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5),
        ),
    ]
