# Generated by Django 3.0.6 on 2020-05-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200519_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_per_topping_large',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_per_topping_small',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
