# Generated by Django 3.0.6 on 2020-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200519_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='available_toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='availableToppings', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_per_topping_large',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price_per_topping_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sub',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
