# Generated by Django 3.0.6 on 2020-05-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200519_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='toppings',
            field=models.ManyToManyField(related_name='regToppings', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='toppings',
            field=models.ManyToManyField(related_name='sicToppings', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='available_toppings',
            field=models.ManyToManyField(related_name='availableToppings', to='orders.Topping'),
        ),
    ]
