# Generated by Django 3.0.6 on 2020-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200519_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('order', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price_per_topping_large',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price_per_topping_small',
        ),
    ]
