# Generated by Django 3.0.6 on 2020-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200522_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Prepairing', 'Prepairing'), ('Cooking', 'Cooking'), ('Delivering', 'Delivering'), ('Done', 'Done')], default='Prepairing', max_length=12),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
