# Generated by Django 3.0.6 on 2020-05-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200524_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='toppings',
        ),
    ]
