# Generated by Django 3.0.6 on 2020-05-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200524_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='available_toppings',
            field=models.ManyToManyField(null=True, related_name='availableToppings', to='orders.Topping'),
        ),
    ]
